[UIKIT-4287] Added ImageGrid ui component.
sendbird/sendbird-uikit-react pull request #703
Opened 2023-08-10 07:58 UTC by liamcho

## For Internal Contributors

* Follow the Scaled Trunk-Based Development workflow(https://trunkbaseddevelopment.com/)
* Branch naming format -> `{type}/TICKET_ID/description`
  * Where type = `feat` / `feature` / `fix` / `chore` / `doc` / `release`
* Always receive PR review approvals
* Rebase your branch with the main branch, and wait for CI to pass
* Squash merge your commit
  * Follow the provided template for both the PR description and squashing to the main branch
  * Use imperative language in the title and description
  * The template is very similar to conventional commits. [Read More](https://www.conventionalcommits.org/en/v1.0.0/)

Template
```
// PR title (Required)
[type]: A short description of the changes in imperative language.

// Section: PR description (Optional)
Add a brief description of the changes that you have involved in this PR.
Bullet points are also fine.

// Section: Footer (Recommended)
// Recommended if you are dealing with SB_ISSUES (Customer issues) or release tickets.
Fixes: [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)

// If you want to add coauthors - for example, if you pair programmed or they made significant contributions to the ideas in the code and you want to thank them.
Co-authored-by: Name <name@example.com>, Name2 <name@example.com>
```

## External Contributions

This project is not yet set up to accept pull requests from external contributors.

If you have a pull request that you believe should be accepted, please contact
the Developer Relations team <developer-advocates@sendbird.com> with details
and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.

2023-08-10 08:00 UTC, sravan-s commented on src/ui/ImageGrid/index.scss
> +}
you should delete this CSS rule

2023-08-10 08:00 UTC, sravan-s commented on src/ui/ImageGrid/__tests__/ImageGrid.spec.js
> +describe('ImageGrid', () => {
If you run `npm t` in local,

2023-08-10 08:03 UTC, sravan-s commented on src/utils/numberToPx.ts
> +  return typeof value === 'number' ? `${value}px` : value;
👍

2023-08-10 08:28 UTC, sravan-s commented on src/ui/ImageGrid/__tests__/ImageGrid.spec.js
> +describe('ImageGrid', () => {
*will explain layers of testing

2023-08-10 08:29 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +        }}
discuss this markup

2023-08-10 08:29 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +  borderRadius = numberToPx(borderRadius);
discuss mutating props

2023-08-10 08:29 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +        { items }
maybe use children

2023-08-10 08:30 UTC, sravan-s commented on src/ui/ImageRenderer/index.tsx
> +                borderRadius: circle ? '50%' : borderRadius,
maybe move logic outside ~

2023-08-10 08:33 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +    }}>
add classname -> move those styles to the class
`sendbird-image--grid-wrap`

2023-08-10 08:36 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +  items,
use -> `children` or `renderItems`

2023-08-10 08:37 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +  items,
children
```
<ImageGrid>
  <>
    <img1 />
    <img2 />
 </>
</ImageGrid>
```

2023-08-10 08:37 UTC, sravan-s commented on src/ui/ImageGrid/index.tsx
> +  items,
`<ImageGrid renderItems={} />`

2023-08-10 08:58 UTC, sravan-s approved these changes

2023-08-10 09:00 UTC, sravan-s requested changes
Apply changes

2023-08-10 09:26 UTC, liamcho commented on src/ui/ImageGrid/index.tsx
> +  items,
Below works
```
<ImageGrid>
  { items }
</ImageGrid>
```

2023-08-10 09:27 UTC, liamcho commented
@sravan-s applied all previous feeds.

2023-08-11 01:58 UTC, sravan-s approved these changes

2023-08-11 01:59 UTC, sravan-s requested changes
Fix lint before merging

2023-08-11 04:50 UTC, sravan-s approved these changes

2023-08-11 04:52 UTC, merged